[package]
name = "get_prime"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level=3
lto=true
strip=true

[dependencies]
num-bigint = { version="0.4.6", features=["rand"]}
num-traits = "0.2.19"
rand = "0.8"
